{% set name = "tinyrecord" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tinyrecord-{{ version }}.tar.gz
  sha256: eb6dc23601be359ee00f5a3d31a46adf3bad0a16f8d60af216cd67982ca75cf4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - tinyrecord
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/eugene-eeo/tinyrecord
  summary: Atomic transactions for TinyDB
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
